"""Validate the pinned manual shapefile and prepare a non-destructive SQL import.

No connection or credentials are used here. Run with Map_Reader's GIS Python.
"""
import hashlib
import json
from pathlib import Path

import geopandas as gpd
from shapely.geometry import MultiPolygon

BASE = Path(__file__).resolve().parent
NAME = "1776_philadelphia_building_parcels"
SOURCE_COMMIT = "29539f1"
TABLE = f'timewalk."{NAME}"'


def quote(value):
    return "'" + str(value).replace("'", "''") + "'"


def main():
    source = BASE / "source" / (NAME + ".shp")
    g = gpd.read_file(source)
    assert len(g) == 51 and g.crs.to_epsg() == 3857
    assert g.is_valid.all() and not g.is_empty.any() and not g.geometry.isna().any()
    assert g.geom_type.isin(["Polygon", "MultiPolygon"]).all()
    assert not g.geometry.normalize().to_wkb().duplicated().any()
    hashes = {p.name: hashlib.sha256(p.read_bytes()).hexdigest()
              for p in sorted((BASE / "source").iterdir())}
    dataset_hash = hashlib.sha256(json.dumps(hashes, sort_keys=True).encode()).hexdigest()
    metric = g.to_crs(32618)
    overlaps = []
    for i in range(len(g)):
        for j in range(i + 1, len(g)):
            area = metric.geometry.iloc[i].intersection(metric.geometry.iloc[j]).area
            if area > 0.01:
                overlaps.append({"source_row_a": i + 1, "source_row_b": j + 1, "area_m2": area})
    out = g.rename(columns={"id": "original_id"}).copy()
    out.insert(0, "source_row", range(1, len(out) + 1))
    out["label_origin"] = "manual"
    out["digitizer"] = "Sunil Prabhu"
    out["target_year"] = 1776
    out["source_map"] = "tw_1776_philadelphia_map_easburn_plan_v2_cog"
    out["split"] = "unassigned"
    out["dataset_sha256"] = dataset_hash
    gpkg = BASE / (NAME + ".gpkg")
    if gpkg.exists():
        gpkg.unlink()
    out.to_file(gpkg, layer=NAME, driver="GPKG")
    restored = gpd.read_file(gpkg, layer=NAME)
    assert len(restored) == len(g) and restored.crs == g.crs
    assert all(a.equals_exact(b, 0) for a, b in zip(g.geometry, restored.geometry))

    rows = []
    for i, row in g.iterrows():
        geom = row.geometry if row.geometry.geom_type == "MultiPolygon" else MultiPolygon([row.geometry])
        original_id = "NULL" if row["id"] != row["id"] else quote(row["id"])
        rows.append(f"({i + 1}, {original_id}, ST_GeomFromWKB(decode('{geom.wkb_hex}', 'hex'),3857))")
    sql = f"""-- Prepared only; no import has been performed.
-- Pinned NYC_Maps main commit {SOURCE_COMMIT}; source SHA256 {dataset_hash}.
-- Run this entire file in one authenticated PostGIS session.
BEGIN;
SET LOCAL lock_timeout = '10s';
SET LOCAL statement_timeout = '60s';
SELECT pg_advisory_xact_lock(hashtext('sunil_manual_parcels_20260907'));
CREATE TEMP TABLE incoming_sunil_parcels (
  source_row bigint PRIMARY KEY, original_id text, geom geometry(MultiPolygon,3857)
) ON COMMIT DROP;
INSERT INTO incoming_sunil_parcels VALUES
""" + ",\n".join(rows) + f""";
DO $$ BEGIN
  IF (SELECT count(*) FROM incoming_sunil_parcels) <> 51 OR
     EXISTS (SELECT 1 FROM incoming_sunil_parcels WHERE geom IS NULL OR ST_IsEmpty(geom) OR NOT ST_IsValid(geom))
  THEN RAISE EXCEPTION 'Incoming geometry validation failed'; END IF;
END $$;
CREATE TABLE IF NOT EXISTS {TABLE} (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  source_row bigint NOT NULL,
  original_id text,
  geom geometry(MultiPolygon,3857) NOT NULL CHECK (ST_IsValid(geom) AND NOT ST_IsEmpty(geom)),
  label_origin text NOT NULL DEFAULT 'manual',
  digitizer text NOT NULL DEFAULT 'Sunil Prabhu',
  source_map text NOT NULL DEFAULT 'tw_1776_philadelphia_map_easburn_plan_v2_cog',
  target_year integer NOT NULL DEFAULT 1776,
  source_repo text NOT NULL DEFAULT 'https://k7oth9.gitea.cloud/TimeWalk/NYC_Maps',
  source_commit text NOT NULL DEFAULT '{SOURCE_COMMIT}',
  dataset_sha256 text NOT NULL DEFAULT '{dataset_hash}',
  imported_at timestamptz NOT NULL DEFAULT now(),
  UNIQUE (dataset_sha256, source_row)
);
-- A populated pre-existing table is allowed only if it is an exact replay.
-- Never overwrite reviewed rows or silently append to another dataset.
DO $$ BEGIN
  IF EXISTS (SELECT 1 FROM {TABLE}) AND (
    (SELECT count(*) FROM {TABLE}) <> 51 OR EXISTS (
      SELECT 1 FROM incoming_sunil_parcels s FULL JOIN {TABLE} t ON s.source_row=t.source_row
      WHERE s.source_row IS NULL OR t.source_row IS NULL
        OR t.dataset_sha256 IS DISTINCT FROM '{dataset_hash}'
        OR t.original_id IS DISTINCT FROM s.original_id OR NOT ST_Equals(t.geom,s.geom)
        OR t.label_origin IS DISTINCT FROM 'manual'
        OR t.source_map IS DISTINCT FROM 'tw_1776_philadelphia_map_easburn_plan_v2_cog'
    )
  ) THEN RAISE EXCEPTION 'Existing table differs; refusing to overwrite or append'; END IF;
END $$;
INSERT INTO {TABLE} (source_row,original_id,geom)
SELECT source_row,original_id,geom FROM incoming_sunil_parcels
ON CONFLICT (dataset_sha256,source_row) DO NOTHING;
CREATE INDEX IF NOT EXISTS sunil_1776_philadelphia_building_parcels_geom_idx ON {TABLE} USING gist (geom);
ALTER TABLE {TABLE} ENABLE ROW LEVEL SECURITY;
COMMENT ON TABLE {TABLE} IS 'Sunil manual parcels; 51 records from NYC_Maps 29539f1. Selected training-label source, replacing Geo-SAM. Not an independently verified benchmark or exhaustive tile annotation.';
DO $$ BEGIN
  IF (SELECT count(*) FROM {TABLE}) <> 51 THEN RAISE EXCEPTION 'Import count mismatch'; END IF;
END $$;
COMMIT;
SELECT count(*) AS parcels, count(*) FILTER (WHERE ST_IsValid(geom)) AS valid,
       array_agg(DISTINCT ST_SRID(geom)) AS srids FROM {TABLE};
"""
    (BASE / "import.sql").write_text(sql)
    (BASE / "validation.json").write_text(json.dumps({
        "count": len(g), "valid": int(g.is_valid.sum()), "crs": "EPSG:3857",
        "empty": 0, "exact_duplicates": 0, "overlaps_over_0_01_m2": overlaps,
        "bounds_wgs84": g.to_crs(4326).total_bounds.tolist(),
        "original_id_null_count": int(g["id"].isna().sum()),
        "source_files_sha256": hashes, "dataset_sha256": dataset_hash,
        "gpkg_geometry_roundtrip_exact": True, "database_import_status": "blocked_authentication"
    }, indent=2) + "\n")
    print(json.dumps({"count":len(g), "overlaps":overlaps, "dataset_sha256":dataset_hash}))


if __name__ == "__main__":
    main()
